modLoader="javafml"
loaderVersion="[34,)"
license="GNU Lesser General Public License v2.1"
issueTrackerURL="https://github.com/CAS-ual-TY/BeaconChunkloaders/issues"

[[mods]]
    modId="beaconchunkloaders"
    version="${file.jarVersion}"
    displayName="Beacon Chunkloaders"
    displayURL="https://github.com/CAS-ual-TY/BeaconChunkloaders"
    logoFile="logo.png"
    credits="LexManos, the original Author, Mojang and the Minecraft Forge Team"
    authors="CAS_ual_TY, LexManos"
    description="Fork of LexManos' ChunkNoGoByeBye but changed to use Beacons instead."
